Commit

diff --git a/.github/workflows/Build CI-CD.yml b/.github/workflows/Build CI-CD.yml
--- a/.github/workflows/Build CI-CD.yml
+++ b/.github/workflows/Build CI-CD.yml
@@ -74,7 +74,7 @@ jobs:
 
     - name: Wait for Mockoon Servers to Start
       run: |
-        for port in 3000 3001 3002 3003; do
+        for port in 3000 3001 3002 3003 3004 3005 3006 3007 3008; do
           for i in {1..10}; do
             if curl --silent http://localhost:$port; then
               echo "Mockoon server on port $port is ready"
@@ -85,22 +85,24 @@ jobs:
           done
         done
 
+
     - name: Check Mockoon Logs
       run: |
         tail ./mockoon-*.log
 
+
     # Step 7: Verify Mockoon Server is Running
-    - name: Verify Mockoon Server
+    - name: Validate Mockoon Endpoints
       run: |
-        curl http://localhost:3000/LPRestClaim
-        curl http://localhost:3001/LPRestParty
-        curl http://localhost:3002/LPRestPolicy
-        curl http://localhost:3003/LPRestProduct
-        curl http://localhost:3004/authz/token
-        curl http://localhost:3005/ulissia-webservices/services/CommonService?wsdl
-        curl http://localhost:3006/ulissia-webservices/services/UnderwritingService?wsdl
-        curl http://localhost:3007/ulissia-webservices/services/WorkflowService?wsdl
-        curl http://localhost:3008/InsuranceServices
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/LPRestClaim || echo "Port 3000 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/LPRestParty || echo "Port 3001 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3002/LPRestPolicy || echo "Port 3002 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3003/LPRestProduct || echo "Port 3003 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3004/authz/token || echo "Port 3004 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3005/ulissia-webservices/services/CommonService?wsdl || echo "Port 3005 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3006/ulissia-webservices/services/UnderwritingService?wsdl || echo "Port 3006 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3007/ulissia-webservices/services/WorkflowService?wsdl || echo "Port 3007 failed"
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:3008/InsuranceServices || echo "Port 3008 failed"
 
 
 
